/*
-- Query: With r as (select Country, Sex, Rate_in_2016, dense_rank () over (partition by Country order by Rate_in_2016 DESC) as r  
from age_standardized_suicide_rates)

SELECT Country, sex, Rate_in_2016 AS sucide
	FROM r 
	WHERE r =1 and sex = ' male' 
    Group by country
-- Date: 2022-10-13 15:21
*/
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Afghanistan,' Male',11.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Albania,' Male',7.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Algeria,' Male',5.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Angola,' Male',14.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Argentina,' Male',15.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Armenia,' Male',10.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Australia,' Male',17.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Austria,' Male',18.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Azerbaijan,' Male',4.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Bahamas,' Male',3.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Bahrain,' Male',8.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Barbados,' Male',1.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Belarus,' Male',39.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Belgium,' Male',22.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Belize,' Male',10.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Benin,' Male',23.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Bhutan,' Male',14.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Bolivia (Plurinational State of),' Male',17.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Bosnia and Herzegovina,' Male',11.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Botswana,' Male',18.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Brazil,' Male',10.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Brunei Darussalam,' Male',6.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Bulgaria,' Male',13.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Burkina Faso,' Male',22.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Burundi,' Male',23.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (CÃ´te d'Ivoire,' Male',32.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Cabo Verde,' Male',24.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Cambodia,' Male',9.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Cameroon,' Male',27.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Canada,' Male',15.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Central African Republic,' Male',18.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Chad,' Male',17.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Chile,' Male',16.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (China,' Male',8.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Colombia,' Male',12.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Comoros,' Male',18.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Congo,' Male',14.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Costa Rica,' Male',13.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Croatia,' Male',19.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Cuba,' Male',16.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Cyprus,' Male',7.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Czechia,' Male',17.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Democratic People's Republic of Korea,' Male',15.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Democratic Republic of the Congo,' Male',15.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Denmark,' Male',13.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Djibouti,' Male',12.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Dominican Republic,' Male',18.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Ecuador,' Male',11.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Egypt,' Male',7.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (El Salvador,' Male',25.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Equatorial Guinea,' Male',31.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Eritrea,' Male',22.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Estonia,' Male',26.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Eswatini,' Male',25.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Ethiopia,' Male',19.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Fiji,' Male',9.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Finland,' Male',21.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (France,' Male',18.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Gabon,' Male',15.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Gambia,' Male',13.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Georgia,' Male',12.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Germany,' Male',14.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Ghana,' Male',16.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Greece,' Male',6.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Grenada,' Male',2.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Guatemala,' Male',4.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Guinea,' Male',13.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Guinea-Bissau,' Male',9.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Guyana,' Male',47.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Haiti,' Male',18.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Honduras,' Male',5.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Hungary,' Male',22.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Iceland,' Male',22.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (India,' Male',19.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Indonesia,' Male',5.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Iran (Islamic Republic of),' Male',5.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Iraq,' Male',5.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Ireland,' Male',18.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Israel,' Male',8.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Italy,' Male',8.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Jamaica,' Male',3.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Japan,' Male',21.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Jordan,' Male',5.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Kazakhstan,' Male',40.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Kenya,' Male',10.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Kiribati,' Male',26.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Kuwait,' Male',3.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Kyrgyzstan,' Male',15.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Lao People's Democratic Republic,' Male',13.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Latvia,' Male',31.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Lebanon,' Male',4.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Liberia,' Male',14.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Libya,' Male',9.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Lithuania,' Male',48.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Luxembourg,' Male',15.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Madagascar,' Male',11.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Malawi,' Male',14.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Malaysia,' Male',9.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Maldives,' Male',4.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Mali,' Male',14.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Malta,' Male',10.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Mauritania,' Male',12.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Mauritius,' Male',13.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Mexico,' Male',8.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Micronesia (Federated States of),' Male',16.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Mongolia,' Male',23.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Montenegro,' Male',13.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Mozambique,' Male',14.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Namibia,' Male',19.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Nepal,' Male',11.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Netherlands,' Male',13.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (New Zealand,' Male',17.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Nicaragua,' Male',19.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Niger,' Male',12.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Nigeria,' Male',18.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Norway,' Male',14.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Oman,' Male',5.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Pakistan,' Male',3.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Panama,' Male',8.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Papua New Guinea,' Male',10.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Paraguay,' Male',12.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Peru,' Male',8.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Philippines,' Male',5.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Poland,' Male',24.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Portugal,' Male',14.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Qatar,' Male',7.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Republic of Korea,' Male',30.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Republic of Moldova,' Male',24.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Republic of North Macedonia,' Male',10.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Romania,' Male',14.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Russian Federation,' Male',48.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Rwanda,' Male',17.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Saint Lucia,' Male',13.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Saint Vincent and the Grenadines,' Male',4.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Samoa,' Male',9.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Sao Tome and Principe,' Male',4.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Saudi Arabia,' Male',5.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Senegal,' Male',20.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Serbia,' Male',17.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Seychelles,' Male',15.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Sierra Leone,' Male',18.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Singapore,' Male',11.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Slovakia,' Male',18.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Slovenia,' Male',22.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Solomon Islands,' Male',9.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Somalia,' Male',12.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (South Africa,' Male',22.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (South Sudan,' Male',8.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Spain,' Male',9.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Sri Lanka,' Male',23.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Sudan,' Male',15.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Suriname,' Male',36.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Sweden,' Male',16.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Switzerland,' Male',16.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Syrian Arab Republic,' Male',4.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Tajikistan,' Male',5.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Thailand,' Male',21.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Timor-Leste,' Male',9.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Togo,' Male',23.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Tonga,' Male',5.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Trinidad and Tobago,' Male',22.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Tunisia,' Male',4.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Turkey,' Male',11.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Turkmenistan,' Male',11.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Uganda,' Male',21.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Ukraine,' Male',35.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (United Arab Emirates,' Male',4.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (United Kingdom of Great Britain and Northern Ireland,' Male',12.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (United Republic of Tanzania,' Male',14.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (United States of America,' Male',21.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Uruguay,' Male',27.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Uzbekistan,' Male',10.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Vanuatu,' Male',8.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Venezuela (Bolivarian Republic of),' Male',7.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Viet Nam,' Male',11.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Yemen,' Male',13.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Zambia,' Male',18.0);
INSERT INTO `` (`Country`,`sex`,`sucide`) VALUES (Zimbabwe,' Male',29.0);
